### ISSUE TITLE
Update AppHeader to get data from server

### ISSUE THREAD

**Issue by derick-montague** [gtmills/phosphor-webui-vue#2]

**Comment by derick-montague** [comment]
Looking at what's currently in master, I am wondering if the icons should be on the right of the text.

**Comment by yoshiemuranaka** [comment]
I'm working off of Jandra's latest proposed design iteration, let me know if you think we should be building towards another design

![image (8)](https://user-images.githubusercontent.com/8097306/71480972-d9cc6580-27b0-11ea-8e67-57af30aaf4ee.png)

**Comment by derick-montague** [comment]
> 

> I'm working off of Jandra's latest proposed design iteration, let me know if you think we should be building towards another design

That works and this will be an opportunity to test the ease of customization. Thank you!

**Comment by derick-montague** [comment]
This issue has been moved to the ibm tracking repo
