### ISSUE TITLE
Mobile navigation design

### ISSUE THREAD

**Issue by yoshiemuranaka** [gtmills/phosphor-webui-vue#66]
We need to define the design for how the navigation should be displayed on small screen.

**Comment by derick-montague** [comment]
In our conversation with Kathy Pine, she agreed that using a hamburger icon when we hit small screen was acceptable. I believe we can use a combination of bootstrap components to accomplish this.

**Comment by derick-montague** [comment]
What has been mixed into the conversation and needs to be determined is the need for both mobile navigation and a manually expandable/collapsible navigation section.  My feeling is that the initial Intel design cannot be implemented simply and the ROI to get it right outweighs the value of the design with dynamic menus. There are many considerations, including various viewport heights that are not accounted for in the design that will be a challenge to implement. 

My opinion is that a recognized small screen navigation pattern is a better investment of time and overall user experience. We also need to determine how to handle the links in the site header.

**Comment by derick-montague** [comment]
Moved to https://github.com/ibm-openbmc/dev/issues/1647 and https://github.com/ibm-openbmc/dev/issues/1646
