### ISSUE TITLE
Overview: Page layout

### ISSUE THREAD

**Issue by derick-montague** [gtmills/phosphor-webui-vue#72]
## Overview
The page has inconsistent styling. Update the layout to use the proposed IBM design. Kathy from Intel was onboard with the section that contained the quicklinks and BMC time. There are still some layout questions we need to work out, but I think we should update the Overview page to use the following design.

### Proposed IBM Design
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/eaf8e17f-8d15-4e50-8fd2-f9fb8ebef15e)

### Outstanding Questions
1. What is the design for the event logs on the Overview page? They are not shown in this design.

**Comment by dixsie** [comment]
Already working on this (quick links and server config update)

**Comment by derick-montague** [comment]
> Already working on this (quick links and server config update)

Working as part of #30? If so, close this story. If not, please move to In Progress.

**Comment by dixsie** [comment]
> > Already working on this (quick links and server config update)
> 
> Working as part of #30? If so, close this story. If not, please move to In Progress.

I am doing it in separate PRs for smaller code drops. #73 covers the quicklinks. 
I will do a PR for events, and one for network information.

**Comment by dixsie** [comment]
Opening separate issues for quicklinks, events and network information layout update.
