### ISSUE TITLE
Update login and overview page routes

### ISSUE THREAD

**Issue by derick-montague** [gtmills/phosphor-webui-vue#81]
## Problem
There are times when the overview page `/` briefly loads before we receive a 403 response. Once we receive the response, it triggers a redirect to the login page.

## Solution
1. Change the route for the login page to `/`
1. Change the route for the overview page to `/overview`
1. Create a 404 page to redirect users to if a page is not found (edge case)

**Comment by gtmills** [comment]
what if I go to / and already have a valid session ?

**Comment by derick-montague** [comment]
> what if I go to / and already have a valid session ?

That's a valid point and something I hadn't considered.

**Comment by derick-montague** [comment]
Assuming you saw it happen today in our demo with the GUI Design workgroup

**Comment by derick-montague** [comment]
This is an edge case that has only been replicated when testing in dev.
